openapi: 3.0.0
info:
  title: API de Tarefas
  version: 1.0.0
  description: API para gerenciamento de tarefas
servers:
  - url: http://localhost:8080
    description: Servidor Local
paths:
  /tasks:
    get:
      summary: Listar todas as tarefas
      description: Retorna uma lista de todas as tarefas
      tags:
        - Task
      responses:
        '200':
          description: Lista de tarefas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Criar uma nova tarefa
      description: Cria uma nova tarefa
      tags:
        - Task
      requestBody:
        description: Objeto de tarefa que precisa ser adicionado
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Tarefa criada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/{id}:
    get:
      summary: Buscar uma tarefa por ID
      description: Retorna uma tarefa específica pelo seu ID
      tags:
        - Task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tarefa encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tarefa não encontrada
    put:
      summary: Atualizar uma tarefa
      description: Atualiza uma tarefa existente pelo seu ID
      tags:
        - Task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Objeto de tarefa que precisa ser atualizado
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Tarefa atualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tarefa não encontrada
    delete:
      summary: Deletar uma tarefa
      description: Deleta uma tarefa existente pelo seu ID
      tags:
        - Task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Tarefa deletada
        '404':
          description: Tarefa não encontrada
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
        descricao:
          type: string
        dataCriacao:
          type: string
          format: date
        dataLimite:
          type: string
          format: date
        finalizada:
          type: boolean
      required:
        - descricao
        - dataCriacao
        - dataLimite
        - finalizada
